//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace FeedbackEntities
{
    public partial class TCourse
    {
        public TCourse()
        {
            this.TFeedback = new HashSet<TFeedback>();
            this.TStudentCourse = new HashSet<TStudentCourse>();
        }

        public int ID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }

        public virtual ICollection<TFeedback> TFeedback { get; set; }
        public virtual ICollection<TStudentCourse> TStudentCourse { get; set; }
    }

    public partial class TFeedback
    {
        public int ID { get; set; }
        public string FeedbackContent { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime PostDate { get; set; }

        public virtual TCourse TCourse { get; set; }
        public virtual TStudent TStudent { get; set; }
    }

    public partial class TStudent
    {
        public TStudent()
        {
            this.TFeedback = new HashSet<TFeedback>();
            this.TStudentCourse = new HashSet<TStudentCourse>();
        }

        public int ID { get; set; }
        public string StudentID { get; set; }

        public virtual ICollection<TFeedback> TFeedback { get; set; }
        public virtual ICollection<TStudentCourse> TStudentCourse { get; set; }
    }

    public partial class TStudentCourse
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime EndDate { get; set; }

        public virtual TCourse TCourse { get; set; }
        public virtual TStudent TStudent { get; set; }
    }

    public partial class vwCourses
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
    }

    public partial class vwFeedbacks
    {
        public int ID { get; set; }
        public string FeedbackContent { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}