//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class COMP306_FeedbackEntities : DbContext
    {
        public COMP306_FeedbackEntities()
            //: base("name=COMP306_FeedbackEntities")
        {
            this.Database.Connection.ConnectionString = "Data Source=localhost; Initial Catalog=COMP306_Feedback; Integrated Security=True;";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TCourse> TCourses { get; set; }
        public DbSet<TFeedback> TFeedbacks { get; set; }
        public DbSet<TStudent> TStudents { get; set; }
        public DbSet<TStudentCourse> TStudentCourses { get; set; }
        public DbSet<vwCourse> vwCourses { get; set; }
        public DbSet<vwFeedback> vwFeedbacks { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> spInsertFeedback(string p01_Content, Nullable<int> p02_CourseID, Nullable<int> p03_StudentID, Nullable<System.DateTime> p04_PostDate)
        {
            var p01_ContentParameter = p01_Content != null ?
                new ObjectParameter("p01_Content", p01_Content) :
                new ObjectParameter("p01_Content", typeof(string));
    
            var p02_CourseIDParameter = p02_CourseID.HasValue ?
                new ObjectParameter("p02_CourseID", p02_CourseID) :
                new ObjectParameter("p02_CourseID", typeof(int));
    
            var p03_StudentIDParameter = p03_StudentID.HasValue ?
                new ObjectParameter("p03_StudentID", p03_StudentID) :
                new ObjectParameter("p03_StudentID", typeof(int));
    
            var p04_PostDateParameter = p04_PostDate.HasValue ?
                new ObjectParameter("p04_PostDate", p04_PostDate) :
                new ObjectParameter("p04_PostDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spInsertFeedback", p01_ContentParameter, p02_CourseIDParameter, p03_StudentIDParameter, p04_PostDateParameter);
        }
    }
}
