//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFFeedbackService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFeedbacks
    {
        public int ID { get; set; }
        public string FeedbackContent { get; set; }
        public string StudentID { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime LastModify { get; set; }
        public int TCourseID { get; set; }
        public int TStudentID { get; set; }
        public string IsAnonymous { get; set; }
    }
}
