//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISTestClient.WCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseObject", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
    [System.SerializableAttribute()]
    public partial class CourseObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
    [System.SerializableAttribute()]
    public partial class FaultFeedbackInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackObject", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
    [System.SerializableAttribute()]
    public partial class FeedbackObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Course_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Course_TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnonymousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PostDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TCourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TStudentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course_Code {
            get {
                return this.Course_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Course_CodeField, value) != true)) {
                    this.Course_CodeField = value;
                    this.RaisePropertyChanged("Course_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course_Title {
            get {
                return this.Course_TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.Course_TitleField, value) != true)) {
                    this.Course_TitleField = value;
                    this.RaisePropertyChanged("Course_Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous {
            get {
                return this.IsAnonymousField;
            }
            set {
                if ((this.IsAnonymousField.Equals(value) != true)) {
                    this.IsAnonymousField = value;
                    this.RaisePropertyChanged("IsAnonymous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModify {
            get {
                return this.LastModifyField;
            }
            set {
                if ((this.LastModifyField.Equals(value) != true)) {
                    this.LastModifyField = value;
                    this.RaisePropertyChanged("LastModify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostDate {
            get {
                return this.PostDateField;
            }
            set {
                if ((this.PostDateField.Equals(value) != true)) {
                    this.PostDateField = value;
                    this.RaisePropertyChanged("PostDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIDField, value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TCourseID {
            get {
                return this.TCourseIDField;
            }
            set {
                if ((this.TCourseIDField.Equals(value) != true)) {
                    this.TCourseIDField = value;
                    this.RaisePropertyChanged("TCourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TStudentID {
            get {
                return this.TStudentIDField;
            }
            set {
                if ((this.TStudentIDField.Equals(value) != true)) {
                    this.TStudentIDField = value;
                    this.RaisePropertyChanged("TStudentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.IFeedbackService")]
    public interface IFeedbackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetAllCourse", ReplyAction="http://tempuri.org/IFeedbackService/GetAllCourseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IISTestClient.WCFServiceReference.FaultFeedbackInfo), Action="http://tempuri.org/IFeedbackService/GetAllCourseFaultFeedbackInfoFault", Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
        IISTestClient.WCFServiceReference.CourseObject[] GetAllCourse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetAllCourse", ReplyAction="http://tempuri.org/IFeedbackService/GetAllCourseResponse")]
        System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.CourseObject[]> GetAllCourseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetCourseByCodeOrTitle", ReplyAction="http://tempuri.org/IFeedbackService/GetCourseByCodeOrTitleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IISTestClient.WCFServiceReference.FaultFeedbackInfo), Action="http://tempuri.org/IFeedbackService/GetCourseByCodeOrTitleFaultFeedbackInfoFault", Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
        IISTestClient.WCFServiceReference.CourseObject[] GetCourseByCodeOrTitle(string codeOrTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetCourseByCodeOrTitle", ReplyAction="http://tempuri.org/IFeedbackService/GetCourseByCodeOrTitleResponse")]
        System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.CourseObject[]> GetCourseByCodeOrTitleAsync(string codeOrTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetFeedbackByCourseID", ReplyAction="http://tempuri.org/IFeedbackService/GetFeedbackByCourseIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IISTestClient.WCFServiceReference.FaultFeedbackInfo), Action="http://tempuri.org/IFeedbackService/GetFeedbackByCourseIDFaultFeedbackInfoFault", Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
        IISTestClient.WCFServiceReference.FeedbackObject[] GetFeedbackByCourseID(int courseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetFeedbackByCourseID", ReplyAction="http://tempuri.org/IFeedbackService/GetFeedbackByCourseIDResponse")]
        System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.FeedbackObject[]> GetFeedbackByCourseIDAsync(int courseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/PostFeedbackByCourseID", ReplyAction="http://tempuri.org/IFeedbackService/PostFeedbackByCourseIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IISTestClient.WCFServiceReference.FaultFeedbackInfo), Action="http://tempuri.org/IFeedbackService/PostFeedbackByCourseIDFaultFeedbackInfoFault", Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
        int PostFeedbackByCourseID(int tcourse_id, string content, bool isAnonymous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/PostFeedbackByCourseID", ReplyAction="http://tempuri.org/IFeedbackService/PostFeedbackByCourseIDResponse")]
        System.Threading.Tasks.Task<int> PostFeedbackByCourseIDAsync(int tcourse_id, string content, bool isAnonymous);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/UpdateByFeedBackID", ReplyAction="http://tempuri.org/IFeedbackService/UpdateByFeedBackIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IISTestClient.WCFServiceReference.FaultFeedbackInfo), Action="http://tempuri.org/IFeedbackService/UpdateByFeedBackIDFaultFeedbackInfoFault", Name="FaultFeedbackInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFFeedbackService.FeedbackObjects")]
        int UpdateByFeedBackID(int id, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/UpdateByFeedBackID", ReplyAction="http://tempuri.org/IFeedbackService/UpdateByFeedBackIDResponse")]
        System.Threading.Tasks.Task<int> UpdateByFeedBackIDAsync(int id, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetCurrentUser", ReplyAction="http://tempuri.org/IFeedbackService/GetCurrentUserResponse")]
        string GetCurrentUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedbackService/GetCurrentUser", ReplyAction="http://tempuri.org/IFeedbackService/GetCurrentUserResponse")]
        System.Threading.Tasks.Task<string> GetCurrentUserAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedbackServiceChannel : IISTestClient.WCFServiceReference.IFeedbackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedbackServiceClient : System.ServiceModel.ClientBase<IISTestClient.WCFServiceReference.IFeedbackService>, IISTestClient.WCFServiceReference.IFeedbackService {
        
        public FeedbackServiceClient() {
        }
        
        public FeedbackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedbackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedbackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IISTestClient.WCFServiceReference.CourseObject[] GetAllCourse() {
            return base.Channel.GetAllCourse();
        }
        
        public System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.CourseObject[]> GetAllCourseAsync() {
            return base.Channel.GetAllCourseAsync();
        }
        
        public IISTestClient.WCFServiceReference.CourseObject[] GetCourseByCodeOrTitle(string codeOrTitle) {
            return base.Channel.GetCourseByCodeOrTitle(codeOrTitle);
        }
        
        public System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.CourseObject[]> GetCourseByCodeOrTitleAsync(string codeOrTitle) {
            return base.Channel.GetCourseByCodeOrTitleAsync(codeOrTitle);
        }
        
        public IISTestClient.WCFServiceReference.FeedbackObject[] GetFeedbackByCourseID(int courseID) {
            return base.Channel.GetFeedbackByCourseID(courseID);
        }
        
        public System.Threading.Tasks.Task<IISTestClient.WCFServiceReference.FeedbackObject[]> GetFeedbackByCourseIDAsync(int courseID) {
            return base.Channel.GetFeedbackByCourseIDAsync(courseID);
        }
        
        public int PostFeedbackByCourseID(int tcourse_id, string content, bool isAnonymous) {
            return base.Channel.PostFeedbackByCourseID(tcourse_id, content, isAnonymous);
        }
        
        public System.Threading.Tasks.Task<int> PostFeedbackByCourseIDAsync(int tcourse_id, string content, bool isAnonymous) {
            return base.Channel.PostFeedbackByCourseIDAsync(tcourse_id, content, isAnonymous);
        }
        
        public int UpdateByFeedBackID(int id, string content) {
            return base.Channel.UpdateByFeedBackID(id, content);
        }
        
        public System.Threading.Tasks.Task<int> UpdateByFeedBackIDAsync(int id, string content) {
            return base.Channel.UpdateByFeedBackIDAsync(id, content);
        }
        
        public string GetCurrentUser() {
            return base.Channel.GetCurrentUser();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentUserAsync() {
            return base.Channel.GetCurrentUserAsync();
        }
    }
}
